import { neon, type NeonQueryFunction } from "@neondatabase/serverless";

// Serverless Postgres (Neon). The connection string comes from DATABASE_URL,
// provisioned via the Vercel Marketplace. Initialised lazily so `next build`
// and typechecking succeed before the env var is wired up.

let _sql: NeonQueryFunction<false, false> | null = null;

function getSql(): NeonQueryFunction<false, false> {
  if (_sql) return _sql;
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is not set");
  _sql = neon(url);
  return _sql;
}

let migrated: Promise<void> | null = null;

function ensureSchema(sql: NeonQueryFunction<false, false>): Promise<void> {
  if (migrated) return migrated;
  migrated = (async () => {
    await sql`
      CREATE TABLE IF NOT EXISTS users (
        id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email         text UNIQUE NOT NULL,
        password_hash text NOT NULL,
        first_name    text NOT NULL,
        last_name     text NOT NULL,
        phone         text NOT NULL,
        birth_date    text NOT NULL,
        street        text NOT NULL,
        city          text NOT NULL,
        country       text NOT NULL,
        postal_code   text NOT NULL,
        balance_eur   double precision NOT NULL DEFAULT 0,
        created_at    timestamptz NOT NULL DEFAULT now()
      )`;
    await sql`
      CREATE TABLE IF NOT EXISTS sessions (
        token      text PRIMARY KEY,
        user_id    integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        created_at timestamptz NOT NULL DEFAULT now(),
        expires_at timestamptz NOT NULL
      )`;
    await sql`
      CREATE TABLE IF NOT EXISTS password_resets (
        token      text PRIMARY KEY,
        user_id    integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        expires_at timestamptz NOT NULL,
        used       integer NOT NULL DEFAULT 0
      )`;
    await sql`
      CREATE TABLE IF NOT EXISTS orders (
        id         text PRIMARY KEY,
        user_id    integer REFERENCES users(id) ON DELETE SET NULL,
        email      text NOT NULL,
        total_eur  double precision NOT NULL,
        currency   text NOT NULL,
        status     text NOT NULL DEFAULT 'paid',
        created_at timestamptz NOT NULL DEFAULT now()
      )`;
    await sql`
      CREATE TABLE IF NOT EXISTS order_items (
        id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id   text NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
        product_id text NOT NULL,
        name       text NOT NULL,
        qty        integer NOT NULL,
        price_eur  double precision NOT NULL,
        game_key   text
      )`;
    await sql`
      CREATE TABLE IF NOT EXISTS ledger (
        id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id    integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        kind       text NOT NULL,
        amount_eur double precision NOT NULL,
        note       text,
        created_at timestamptz NOT NULL DEFAULT now()
      )`;
  })();
  return migrated;
}

// Returns the Neon query tag after guaranteeing the schema exists. All data
// access goes through this so a cold serverless instance self-heals its tables.
export async function db(): Promise<NeonQueryFunction<false, false>> {
  const sql = getSql();
  await ensureSchema(sql);
  return sql;
}

export interface UserRow {
  id: number;
  email: string;
  password_hash: string;
  first_name: string;
  last_name: string;
  phone: string;
  birth_date: string;
  street: string;
  city: string;
  country: string;
  postal_code: string;
  balance_eur: number;
  created_at: string;
}
